### ISSUE TITLE
[Discussion] Is it necessary to still support PhantomJS Driver?!

### ISSUE THREAD

**Issue by mabartos** [arquillian/arquillian-extension-drone#349]
@bartoszmajsak Hi! I just wanted to ask, whether it's necessary to still support PhantomJS, which is not maintained anymore; AFAIK.

**Comment by bartoszmajsak** [comment]
Are there any alternative people switched to that we don't support?

**Comment by jonkoops** [comment]
PhantomJS has been EOL since 2018. It was also never a 'real' browser, but rather a runtime attempting to fake a browser. At this point testing in it should actually be considered harmful, since it doesn't reflect any real world scenario code would be running in.

I'd recommend to remove it and bump a major version honestly.

**Comment by jonkoops** [comment]
Same goes for the InternetExplorerDriver by the way.

**Comment by lprimak** [comment]
No. It's deprecated with Selenium 4.

**Comment by mabartos** [comment]
Suppressed by https://github.com/arquillian/arquillian-extension-drone/issues/402
