### ISSUE TITLE
Add support for Appium

### ISSUE THREAD

**Issue by vinsguru** [arquillian/arquillian-extension-drone#86]
Arquillian Drone / Graphene are simply awesome. It would be great if we could add support for Appium - https://github.com/appium/appium

Appium has become industry standard for mobile automation. We need a drone extension for Appium.

**Comment by bartoszmajsak** [comment]
That might be a good added value to our toolset. Thanks for this suggestion. Would you be interested in helping us implementing this feature?

**Comment by vinsguru** [comment]
@bartoszmajsak , Yes, i would love to contribute.

**Comment by bartoszmajsak** [comment]
Awesome! Let us know if you will need any help with the implementation!

**Comment by MatousJobanek** [comment]
Hi @vinsguru,
Appium has been on my todo list for quite a long time, unfortunately, I haven't got to it because of lack of time. I would be really thankful if tried to implement this.
You can take a look on two current extensions (for Saucelabs and BrowserStack) https://github.com/arquillian/arquillian-extension-drone/tree/master/extension to get some inspiration.
If you need to download/manage some binary, you can take a look how it is done for webdrivers and Selenium Server jar: https://github.com/arquillian/arquillian-extension-drone/tree/master/drone-webdriver/src/main/java/org/jboss/arquillian/drone/webdriver/binary/handler
If you have any question don't hesitate to ask.

**Comment by vinsguru** [comment]
@MatousJobanek , Thanks,
I have been using BrowserStack extn for a while & it works great. In fact, I was also thinking of checking the BrowserStack extn for Appium impl. 

Currently I have been working on Graphene visual validation using arquillian-rusheye. Once it s done, I will start working on the appium.

**Comment by MatousJobanek** [comment]
latest related forum thread: https://developer.jboss.org/message/973421

**Comment by vmuzikar** [comment]
Created PR https://github.com/arquillian/arquillian-extension-drone/pull/101 for this

**Comment by MatousJobanek** [comment]
PR has been landed in https://github.com/arquillian/arquillian-extension-drone/commit/bf4eaac0e0f3488afa6b841680bde4a174d94934
Will be part of Drone 2.3.0
