### ISSUE TITLE
Drone - TestNg Parallel testing support

### ISSUE THREAD

**Issue by vinsguru** [arquillian/arquillian-extension-drone#87]
@MatousJobanek @lordofthejars 

I am a huge fan of Arquillian Drone and Graphene. When i show Drone/Graphene features to others, (like Injection, page fragments, fluent wait API etc), everyone seems to love Drone/Graphene a lot. But in the end, I hear this as an issue/drawback of this drone from the people who explored this.  **It does not support parallel testing!!** 

Parallel testing is a must-have feature nowadays. I would suggest arquillian team to take a look at this - It would bring more users to our Arquillian community. 

Exception:
 

> java.lang.IllegalStateException: No TestRunnerAdaptor found, @BeforeSuite has not been called
>   at org.jboss.arquillian.testng.Arquillian.verifyTestRunnerAdaptorHasBeenSet(Arquillian.java:263)
>   at org.jboss.arquillian.testng.Arquillian.arquillianBeforeClass(Arquillian.java:107)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>   at java.lang.reflect.Method.invoke(Method.java:497)
>   at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
>   at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
>   at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
>   at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
>   at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
>   at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>   at java.lang.Thread.run(Thread.java:745)

**Comment by bartoszmajsak** [comment]
It is possible. You can at least run test classes in parallel when using drone (e.g. through surefire). Parallel class and methods execution is not possible at the moment.

**Comment by vinsguru** [comment]
@bartoszmajsak , 

Nope, It does not.

```
<plugin>
     <groupId>org.apache.maven.plugins</groupId>
     <artifactId>maven-surefire-plugin</artifactId>
      <version>2.20</version>
     <configuration>
		<suiteXmlFiles>
		   <suiteXmlFile>testng1.xml</suiteXmlFile>
		   <suiteXmlFile>testng2.xml</suiteXmlFile>
		</suiteXmlFiles>	
          <properties>
            <property>
              <name>suitethreadpoolsize</name>
              <value>2</value>
            </property>
          </properties>			
     </configuration>
</plugin>

```
All the tests in testng2.xml fails saying - 

> org.jboss.arquillian.graphene.enricher.exception.PageObjectInitializationException: Can not instantiate Page Object 
> Caused by: java.lang.NullPointerException
> 	at org.jboss.arquillian.graphene.enricher.AbstractSearchContextEnricher.enrichRecursively(AbstractSearchContextEnricher.java:67)
> 	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.setupPage(PageObjectEnricher.java:97)
> 	at org.jboss.arquillian.graphene.enricher.PageObjectEnricher.enrich(PageObjectEnricher.java:75)


If i change the suitethreadpoolsize to 1, then all the tests are working fine.

**Comment by bartoszmajsak** [comment]
Could you please provide reproducer project on GitHub? This will help us narrowing the issue.

**Comment by vinsguru** [comment]
@bartoszmajsak 

Please check this project.

https://github.com/vinsguru/arquillian-testng-parallel

**Comment by bartoszmajsak** [comment]
Great, thanks a lot! I'm on holidays now but will check with the other community members to follow up.

**Comment by vinsguru** [comment]
@bartoszmajsak , Were you able to find some time to take a look?

**Comment by bartoszmajsak** [comment]
@vinsguru not yet. But hopefully soon. Been on and off due to holidays last month.

**Comment by vinsguru** [comment]
@bartoszmajsak if possible, please take a look at this request.

**Comment by jagdeepjain** [comment]
Its a need to run parallel tests now a days to save on execution timings. Can we have a support for methods/classes via parallel test execution?

Also I tried the way as it was given https://github.com/vinsguru/arquillian-testng-parallel it works for me but that too tests are running sequential.

**Comment by NScheeren** [comment]
Hi all, is there any word on this yet? I´m currently trying to get some loadtesting going and this might really help :)

**Comment by rameshsah** [comment]
would be very helpful feature and will reduce execution time significantly.  Is there a workaround while we look for a proper fix?

**Comment by JyotiShah** [comment]
Any updates on this fix. Waiting to implement the parallel execution in my project..

**Comment by vinsguru** [comment]
@dipak-pawar Is this something you could take a look at?

**Comment by SarahFaller213** [comment]
Hello! My name is Sarah and I am interested in taking up the challenge! @bartoszmajsak. Are there any updates on the state of this problem?

**Comment by bartoszmajsak** [comment]
Hi @SarahFaller213. I'm very happy to see your interest. I am afraid that this issue is in the same state as when originally reported. Did you have a chance to take a look at referenced reproducer projects?

**Comment by SarahFaller213** [comment]
Hi!

Yes a little. I am also able to reproduce it on my end. I am trying to get
context for this problem. Do you think the issue is in the adaptor for
arquillian and testNG? Let me know if there any information you can provide
me with!

Sarah

**Comment by SarahFaller213** [comment]
I have been taking a look at the issue and it seems like the testRunnerAdaptor (deployableTest) is not getting initialized correctly when a new thread is spawned. It is able to see the correct object but the content is null and not initialized properly. Below is the output of the code with some print statements I added. The number (#) refers to lines of code

++++++++---------------+++++++++BeforeSuite+++++++++++--------------+++++++++++++++++++
Current thread: main **(1)**
i am in setting the adaptor
++++++++--BEFORE SUITE DEPLOYABLE ADDRESSS++
java.lang.ThreadLocal@38022758
++++++++---------------++++++++++BeforeClass++++++++++--------------+++++++++++++++++++
Current thread: testNG-tests-1 **(2)**
++++++++--before class DEPLOYABLE ADDRESSS++
java.lang.ThreadLocal@38022758
this is the adaptor in before class = null **(3)**
in verify test runner adaptor
++++++++--verify test runner DEPLOAYBALETEST ADDRESSS++
java.lang.ThreadLocal@38022758
NULLCHECK IS TRUE++++++++++++++++

Here you can see that the main thread (**1)** in Before suite sets the adaptor. And the address of that is java.lang.ThreadLocal@38022758. 
Then TestNG spawns a new thread for before class method called  testNG-tests-1 (**2)**. The object of the adaptor has the same address: java.lang.ThreadLocal@38022758. When we try to do System.err.println("++++++++++---------thisistheadaptorinbeforeclass"+deployableTest.get()); **(3)**

It prints null. The content does not exist. Then in BeforeClass, once verifyTestRunnerAdaptorHasbeenSet() method is executed the null check is true, and the illegalStateException is thrown causing the program to crash. 

I did some research on local thread which is the type of TestRunnerAdaptor:

ThreadLocal<TestRunnerAdaptor>deployableTest= new ThreadLocal<TestRunnerAdaptor>();


https://stackoverflow.com/questions/6327913/how-to-continue-object-from-threadlocal-in-child-thread

http://tutorials.jenkov.com/java-concurrency/threadlocal.html

It seems like what is needed is InheritableThreadLocal. 

"The InheritableThreadLocal class is a subclass of ThreadLocal. Instead of each thread having its own value inside a ThreadLocal, the InheritableThreadLocal grants access to values to a thread and all child threads created by that thread."

So I changed it to 
privatestaticInheritableThreadLocal<TestRunnerAdaptor>deployableTest=newInheritableThreadLocal<TestRunnerAdaptor>();

And now I am actually able to run the tests in parallel on my end. 

Please let me know you thoughts on this.
